### ISSUE TITLE
80mm Spindle

### ISSUE THREAD

**Issue by marianoronchi** [RootCNC/Root-4-CNC#1]
Pete I'm planning to make an R4 and my spindle has an 80mm diameter. Do you believe that it's possible to get the 80mm version of the spindle mount if not, no problem I will redraw it. By the way I'm creating a complete 3D model of it so if you want it just let me know the file format that you prefer.

![image](https://user-images.githubusercontent.com/11918861/94485043-b86f2e80-01b3-11eb-997e-4709ad121641.png)

Thanks!

**Comment by RootCNC** [comment]
@marianoronchi Hi, the 3D model is looking niceeee!

I have since added a new commit to the project for an 80mm Spindle - [LINK](Source/STL_Files/Z_Axis_MotorMount_85mm.STL)

I've not printed this nor do I have a 80mm spindle; please could you let me know how this goes?

I'll leave this issue open until I hear its alright.

**Comment by RootCNC** [comment]
Incorrect file name was updated - please see this [LINK](https://github.com/RootCNC/Root-4-CNC/blob/master/Source/STL_Files/Spindle_Mount_80mm.STL)

**Comment by RootCNC** [comment]
has anyone printed this file - was it ok?

**Comment by marianoronchi** [comment]
Pete I'll print it this week, let you know... Best regards.

**Comment by marianoronchi** [comment]
> has anyone printed this file - was it ok?

Pete, I just printed the 80mm spindle mount (Some pictures attached) everything looks ok, I just printed it without supports so on the vents the piece has some glitches. Mi spindle it's really heavy and regardless that I'm used ABS, 4 perimeters, 50% Infill, and 4 top/bottom layers I have the sensation that the piece is not strong enough, but I'll give it a try and let you know.

Best regards and thanks for your hard work.

Have a happy new year.

**Comment by RootCNC** [comment]
@marianoronchi - Those settings seem about right, well at least what I was expecting anyway. The print looks useable from the photos with the absence of support materials! nice work. it'll be interesting to know the feedback of mounting it into the carriage blocks - mine was a little fiddly and I think this carriage might be a tad harder. 

Happy new year too :)

**Comment by readeral** [comment]
@marianoronchi did the spindle mount work out for you?

**Comment by Woszu1981** [comment]
marianoronchi can you share a complete 3D model?
