### ISSUE TITLE
Recommended / Tested Infill %?

### ISSUE THREAD

**Issue by Xgl0baltk** [RootCNC/Root-4-CNC#3]
Could the recommended Infill (if there are any preferences stress and durabilitywise) be added to the BOM?

Just slicing right now, 
1x Y_Axis_FF 1x Y_Axis_FK
0.6 nozzle, 0.32mm Layer hight 50mm/s
50% Gyroid infill: 1 day 11 hours  659gr
40% Gyroid infill: 1 day 6 hours 6 Minutes 531gr
30% Gyroid infill: 21 hours 58 minutes  453gr

quite a difference at just 2 parts and yes i am biased towards Gyroid since it is pretty :) and can take a lot because of the changing infill direction

**Comment by RootCNC** [comment]
The Root 4 is based heavily on the Root 3 CNC machine - please check this out for my recommendation - [Link](https://rootcnc.com/machines/root-3/how-to-print-r3/)
