### ISSUE TITLE
Need a dxf for the dust shoe base.

### ISSUE THREAD

**Issue by BayouBurner** [RootCNC/Root-4-CNC#7]
Need a .dxf for the dust shoe base. Thanks !

**Comment by RootCNC** [comment]
The repo has been updated to include the DustShow_base File in PDF and DXF format. link to [Commit](https://github.com/RootCNC/Root-4-CNC/commit/8024fa9bb7cd9faec34879de3d77e86b2150a388)

**Comment by BayouBurner** [comment]
See the file, don't see any way of downloading it. What am I missing? I've downloaded files before, this one seems to be different ?
